title: Hof Niederfeld Limburg-Ahlbach
phone-display: "06433 4507"
phone-href: "+4964334507"
mail: info@hof-niederfeld.de  # schmitt-ahlbach@t-online.de
address:
  street: "Hof Niederfeld 1"
  zip: "65554"
  city: "Limburg-Ahlbach"
  country: "Deutschland"