title: "Hof Niederfeld Limburg-Ahlbach"
description: "Hof Niederfeld in Limburg-Ahlbach: Regionaler Miscanthus, Betonsteine, Lebensmittel wie Nudeln, Eier & Honig, Ferienwohnung sowie Lohnarbeiten für Landwirtschaft & Einstreu."

url: "https://www.hof-niederfeld.de"
baseurl: ""

phone-display: "06433 4507"
phone-href: "+4964334507"
mail: "info@hof-niederfeld.de"  # schmitt-ahlbach@t-online.de

address:
  street: "Hof Niederfeld 1"
  zip: "65554"
  city: "Limburg-Ahlbach"
  country: "Deutschland"
